name: fui
description: fui
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  uuid: ^3.0.1
  flutter_markdown: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: PuHuiTi
      fonts:
        - asset: fonts/Alibaba-PuHuiTi-Light.ttf
          weight: 300
        - asset: fonts/Alibaba-PuHuiTi-Regular.ttf
          weight: 400
        - asset: fonts/Alibaba-PuHuiTi-Medium.ttf
          weight: 500
        - asset: fonts/Alibaba-PuHuiTi-Bold.ttf
          weight: 700
        - asset: fonts/Alibaba-PuHuiTi-Heavy.ttf
          weight: 900
